# Generated by Django 4.1.3 on 2022-12-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_product_images_alter_shop_imageurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryin',
        ),
        migrations.AddField(
            model_name='category',
            name='categoryin',
            field=models.ManyToManyField(to='app.category'),
        ),
    ]
