# Generated by Django 4.1.3 on 2022-12-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_category_categoryin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='whcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='whcategory',
            field=models.ManyToManyField(blank=True, to='app.category'),
        ),
    ]
