# Generated by Django 4.1.3 on 2023-01-13 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_productimages_ismain'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagebefore', models.FileField(upload_to='')),
                ('imageafter', models.FileField(upload_to='')),
                ('done', models.BooleanField(default=False)),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
