# Generated by Django 4.1.3 on 2023-01-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_makewatermark_imagebefore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makewatermark',
            name='imageafter',
            field=models.FileField(upload_to='media/afterWatermark/'),
        ),
    ]
