# Generated by Django 4.1.3 on 2023-01-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_makewatermark_imageafter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makewatermark',
            name='imageafter',
            field=models.FileField(upload_to='afterWatermark/'),
        ),
        migrations.AlterField(
            model_name='makewatermark',
            name='imagebefore',
            field=models.FileField(upload_to='beforeWatermark/'),
        ),
    ]
