# Generated by Django 4.1.3 on 2023-02-10 14:24

import app.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_profile_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makewatermark',
            name='imageafter',
            field=models.FileField(upload_to=functools.partial(app.models.pathAndRename, *(), **{'upload': 'afterWatermark'})),
        ),
        migrations.AlterField(
            model_name='makewatermark',
            name='imagebefore',
            field=models.FileField(upload_to=functools.partial(app.models.pathAndRename, *(), **{'upload': 'beforeWatermark'})),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.FileField(upload_to=functools.partial(app.models.pathAndRename, *(), **{'upload': ''})),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(upload_to=functools.partial(app.models.pathAndRename, *(), **{'upload': 'profileAvatar'})),
        ),
        migrations.AlterField(
            model_name='shop',
            name='imageUrl',
            field=models.FileField(upload_to=functools.partial(app.models.pathAndRename, *(), **{'upload': ''})),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
