# Generated by Django 4.1.3 on 2023-02-10 16:04

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_alter_makewatermark_imageafter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryin',
        ),
        migrations.RemoveField(
            model_name='makewatermark',
            name='imageafter',
        ),
        migrations.RemoveField(
            model_name='makewatermark',
            name='imagebefore',
        ),
        migrations.RemoveField(
            model_name='makewatermark',
            name='touser',
        ),
        migrations.RemoveField(
            model_name='product',
            name='whcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='whshop',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='ismain',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='toproduct',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='userfrom',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='userto',
        ),
        migrations.AddField(
            model_name='category',
            name='in_category',
            field=models.ManyToManyField(blank=True, null=True, to='app.category'),
        ),
        migrations.AddField(
            model_name='makewatermark',
            name='image_after',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(app.models.pathAndRename, *(), **{'upload': 'afterWatermark'})),
        ),
        migrations.AddField(
            model_name='makewatermark',
            name='image_before',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(app.models.pathAndRename, *(), **{'upload': 'beforeWatermark'})),
        ),
        migrations.AddField(
            model_name='makewatermark',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='in_category',
            field=models.ManyToManyField(blank=True, null=True, to='app.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shop'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productimages',
            name='to_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AddField(
            model_name='shop',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(app.models.pathAndRename, *(), **{'upload': ''})),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='app.profile'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(app.models.pathAndRename, *(), **{'upload': ''})),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(app.models.pathAndRename, *(), **{'upload': 'profileAvatar'})),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
