# Generated by Django 4.1.3 on 2023-02-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_category_categoryin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='in_category',
            field=models.ManyToManyField(blank=True, to='app.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_category',
            field=models.ManyToManyField(blank=True, to='app.category'),
        ),
    ]
